// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char THING_ID[] = "962fa315-fc24-4123-ae30-7c87a31acd0d";

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onAverageTempChange();
void onAverageLightChange();
void onAverageHumidityChange();

float humidity;
float temperature;
int light;
int moistPrecentage;
float averageTemp;
int averageLight;
float averageHumidity;

void initProperties(){

  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(humidity, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(temperature, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(light, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(moistPrecentage, READ, 60 * SECONDS, NULL);
  ArduinoCloud.addProperty(averageTemp, READWRITE, ON_CHANGE, onAverageTempChange);
  ArduinoCloud.addProperty(averageLight, READWRITE, ON_CHANGE, onAverageLightChange);
  ArduinoCloud.addProperty(averageHumidity, READWRITE, ON_CHANGE, onAverageHumidityChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
